openapi: 3.0.0
info:
  title: Campus Wall API
  version: "1.0.0"
  description: API for campus social features

servers:
  - url: /api/v1

tags:
  - name: auth
  - name: posts
  - name: walls
  - name: internships
  - name: marketplace
  - name: coins

paths:

  # =================== Auth ===================
  /auth/email/code:
    post:
      tags: [auth]
      summary: Send email verification code
      operationId: sendEmailCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendEmailCodeRequest"
      responses:
        "200":
          description: Verification code sent

  /auth/email/verify:
    post:
      tags: [auth]
      summary: Verify email code and authenticate user
      operationId: verifyEmailCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyEmailCodeRequest"
      responses:
        "200":
          description: Email verified / user authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  user:
                    $ref: "#/components/schemas/UserDTO"

  /auth/password:
    post:
      tags: [auth]
      summary: Set or change password
      operationId: setPassword
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetPasswordRequest"
      responses:
        "200":
          description: Password updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"

  /auth/login/password:
    post:
      tags: [auth]
      summary: Login with email and password
      operationId: loginWithPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PasswordLoginRequest"
      responses:
        "200":
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  user:
                    $ref: "#/components/schemas/UserDTO"

  # =================== Posts ===================
  /posts:
    post:
      tags: [posts]
      operationId: createPost
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePostRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostDTO"
    get:
      tags: [posts]
      operationId: listPosts
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: wall
          schema:
            type: string
            enum: [campus, national]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PostDTO"

  /posts/{postId}/comments:
    post:
      tags: [posts]
      operationId: addComment
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCommentRequest"
      responses:
        "201":
          description: Comment added

  /posts/{postId}/likes:
    post:
      tags: [posts]
      operationId: likePost
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Liked

  # =================== Walls ===================
  /walls/campus:
    get:
      tags: [walls]
      operationId: getCampusWall
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PostDTO"

  /walls/national:
    get:
      tags: [walls]
      operationId: getNationalWall
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PostDTO"

  # =================== Internships ===================
  /internships:
    post:
      tags: [internships]
      operationId: createInternship
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateInternshipRequest"
      responses:
        "201":
          description: Created
    get:
      tags: [internships]
      operationId: listInternships
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK

  # =================== Marketplace ===================
  /marketplace:
    post:
      tags: [marketplace]
      operationId: createItem
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateItemRequest"
      responses:
        "201":
          description: Created
    get:
      tags: [marketplace]
      operationId: listItems
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK

  # =================== Coins ===================
  /coins/claim:
    post:
      tags: [coins]
      operationId: claimCoins
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Claimed
  /coins/balance:
    get:
      tags: [coins]
      operationId: getBalance
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoinBalanceDTO"

components:
  schemas:

    # ----- Auth -----
    UserDTO:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        isVerified:
          type: boolean
        passwordSet:
          type: boolean
          description: true if user has already set a password
        createdAt:
          type: string
          format: date-time

    SendEmailCodeRequest:
      type: object
      required: [email, purpose]
      properties:
        email:
          type: string
          format: email
        purpose:
          type: string
          enum: [register, login, reset_password]

    VerifyEmailCodeRequest:
      type: object
      required: [email, code]
      properties:
        email:
          type: string
          format: email
        code:
          type: string
          example: "839214"

    SetPasswordRequest:
      type: object
      required: [password]
      properties:
        oldPassword:
          type: string
          description: Required if changing existing password
        password:
          type: string
          minLength: 8

    PasswordLoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    # ----- Posts -----
    CreatePostRequest:
      type: object
      required: [content]
      properties:
        content:
          type: string

    PostDTO:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time

    CreateCommentRequest:
      type: object
      required: [text]
      properties:
        text:
          type: string

    # ----- Internships -----
    CreateInternshipRequest:
      type: object
      properties:
        company:
          type: string
        role:
          type: string
        salary:
          type: string

    # ----- Marketplace -----
    CreateItemRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: float

    # ----- Coins -----
    CoinBalanceDTO:
      type: object
      properties:
        balance:
          type: integer

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
